language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.5"
    - "pypy"
    - "pypy3"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bce2445da932b9c1bed7
    on_success: change
    on_failure: always
    on_start: never

script: nosetests -v test
